name: template_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0-217.0.dev

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  desktop_window: ^0.4.0
  go_router: ^14.2.7
  getwidget: ^4.0.0
  riverpod: ^2.5.1
  logger: ^2.4.0
  path: ^1.9.0
  path_provider: ^2.1.4
  icons_launcher: ^2.1.7
  intl_utils: ^2.8.7
  uuid: ^4.5.0
  flutter_localizations:
    sdk: flutter
  intl: any
  shared_preferences: ^2.3.2
  flutter_riverpod: ^2.5.1

dev_dependencies:
  build_runner: ^2.4.12
  change_app_package_name: ^1.3.0
  extra_pedantic: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/icons/
    - assets/images/
flutter_intl:
  enable: true
  main_locale: en

icons_launcher:
  image_path: "assets/images/icons/app_icon.jpg"
  platforms:
    linux:
      enable: true
    windows:
      enable: true
    macos:
      enable: true
    android:
      enable: true
    ios:
      enable: true
    web:
      enable: true
